-- CreateTable
CREATE TABLE "Positions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "j1" REAL NOT NULL,
    "j2" REAL NOT NULL,
    "j3" REAL NOT NULL
);
